name: Deploy to app engine

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: touch .env
      - run: echo MONGODB_URI=${{ MONGODB_URI }} >> .env
      - run: echo MONGODB_DATABASE=${{ MONGODB_DATABASE }} >> .env
      - run: echo JWT_SECRET=${{ JWT_SECRET }} >> .env
      - run: cat .env
      - run: npm install
      - run: npm run build

      - name: Deploy to GAE 
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        with:
          args: app deploy app.yaml